#!/usr/bin/env python3
# =========================================================================
# PROJECT AWHC-88: ATMOSPHERIC WATER HARVESTER DIGITAL TWIN
# Verification Module: Psychrometric Dew-Point Crossing & Pressure Twin
# Licensed under CERN-OHL-S-2.0 (Strongly Reciprocal Open Hardware)
# =========================================================================

import numpy as np

def calculate_dew_point(temp_c, rh_percent):
    """
    Calculates the ambient dew point temperature using the Magnus-Tetens formula.
    """
    a = 17.27
    b = 237.7
    alpha = ((a * temp_c) / (b + temp_c)) + np.log(rh_percent / 100.0)
    dew_point = (b * alpha) / (a - alpha)
    return dew_point

def run_thermodynamic_validation():
    print("=" * 75)
    print(" PROJECT AWHC-88: SOLID-STATE CONDENSER THERMODYNAMIC VALIDATION")
    print("=" * 75)
    
    # --- FIELD INPUT TELEMETRY (Hyper-Arid Extreme Desert Context) ---
    ambient_temp_c = 42.0          # Ambient desert air inlet temperature (°C)
    ambient_rh_pct = 12.0          # Extremely low relative humidity percentage (%)
    inlet_velocity_ms = 12.0       # Entry velocity generated by cardioid intake plenum (m/s)
    venturi_compression_ratio = 5.5 # Geometric area pinch factor of micro-Venturi tubes
    
    print(f"[*] Analyzing Environmental Boundary Telemetry...")
    print(f"    -> Ambient Dry-Bulb Temperature : {ambient_temp_c:.1f}°C")
    print(f"    -> Ambient Relative Humidity    : {ambient_rh_pct:.1f}%")
    print(f"    -> Plenum Induction Velocity    : {inlet_velocity_ms:.1f} m/s")
    print(f"    -> Venturi Compression Ratio    : {venturi_compression_ratio:.1f}x")
    print("-" * 75)
    
    # 1. PSYCHROMETRIC DEW-POINT BASELINE CHECK
    target_dew_point_c = calculate_dew_point(ambient_temp_c, ambient_rh_pct)
    print(f"[*] Baseline Psychrometric Calculation:")
    print(f"    -> Target Dew-Point Threshold   : {target_dew_point_c:.2f}°C")
    print(f"    -> Thermal Gap to Condensation  : {(ambient_temp_c - target_dew_point_c):.2f}°C")
    print("-" * 75)
    
    # 2. FLUID KINEMATICS ACCELERATION & TEMPERATURE CRASH SIMULATION
    # Air velocity accelerates based on the conservation of mass (incompressible approximation for slots)
    throat_velocity_ms = inlet_velocity_ms * venturi_compression_ratio
    
    # Ideal gas expansion and pressure drops drop temperature via expansion mechanics
    # Delta T estimated via localized fluid dynamic static pressure drop (Delta P = 0.5 * rho * delta(V^2))
    air_density_kg_m3 = 1.12
    static_pressure_drop_pa = 0.5 * air_density_kg_m3 * (throat_velocity_ms**2 - inlet_velocity_ms**2)
    pressure_drop_kpa = static_pressure_drop_pa / 1000.0
    
    # Temperature expansion cooling coefficient modeled for high-velocity local fluid slots (approx 0.35°C/kPa drop)
    fluid_cooling_coefficient = 0.35
    temperature_drop_c = pressure_drop_kpa * fluid_cooling_coefficient
    vortex_core_temperature_c = ambient_temp_c - temperature_drop_c
    
    print(f"[*] Fluid Dynamic Expansion Core Analytics:")
    print(f"    -> Internal Throat Air Velocity : {throat_velocity_ms:.1f} m/s")
    print(f"    -> Localized Static Pressure Drop: -{pressure_drop_kpa:.2f} kPa")
    print(f"    -> Geometric Induced Temperature Drop : -{temperature_drop_c:.2f}°C")
    print(f"    -> Calculated Core Extraction Temp : {vortex_core_temperature_c:.2f}°C")
    print("-" * 75)
    
    # 3. PHASE EXPANSION CHECKMATE EVALUATION
    print(f"[*] Final System Manifest Verification:")
    if vortex_core_temperature_c <= target_dew_point_c:
        print(" [SUCCESS] Geometric Expansion Crosses Dew-Point Target.")
        print(f"           Instantaneous Solid-State Condensation Active at Core Fins.")
    else:
        # Auxiliary cooling loop required if expansion alone doesn't clear the gap
        aux_cooling_required_c = vortex_core_temperature_c - target_dew_point_c
        print(" [WARNING] Expansion cooling alone insufficient for phase change.")
        print(f"           Concentric thermoelectric Seebeck sink must supply additional -{aux_cooling_required_c:.2f}°C.")
    print("=" * 75)

if __name__ == "__main__":
    run_thermodynamic_validation()
  
